# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: tf-goreleaser-ecr
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    # - go generate ./...

builds:
  - 
    id: tf-goreleaser-ecr_binaries
    ldflags:
    - -s -w 
    - -X github.com/prabhatsharma/tf-goreleaser-ecr/pkg/meta/v1.Version={{.Version}} 
    - -X github.com/prabhatsharma/tf-goreleaser-ecr/pkg/meta/v1.BuildDate={{.Date}}   # https://goreleaser.com/customization/templates/
    - -X github.com/prabhatsharma/tf-goreleaser-ecr/pkg/meta/v1.CommitHash={{.Commit}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      # - windows
      # - darwin
      # - freebsd
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    main: ./cmd/tf-goreleaser-ecr/main.go
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
dockers:
  - image_templates:
      - public.ecr.aws/prabhat/tf-goreleaser-ecr:{{ .Version }}-amd64
    use: buildx
    skip_push: "false"
    build_flag_templates:
    - "--platform=linux/amd64"
    extra_files:
      - go.mod
      - go.sum
      - pkg
      - cmd
      - web
      - embed.go
  - image_templates:
      - public.ecr.aws/prabhat/tf-goreleaser-ecr:{{ .Version }}-arm64
    use: buildx
    skip_push: "false"
    build_flag_templates:
    - "--platform=linux/arm64/v8"
    extra_files:
      - go.mod
      - go.sum
      - pkg
      - cmd
      - web
      - embed.go
  - image_templates:
      - public.ecr.aws/prabhat/tf-goreleaser-ecr:{{ .Version }}-armv7 
    use: buildx
    skip_push: "false"
    build_flag_templates:
    - "--platform=linux/arm/v7"
    extra_files:
      - go.mod
      - go.sum
      - pkg
      - cmd
      - web
      - embed.go
  - image_templates:
      - public.ecr.aws/prabhat/tf-goreleaser-ecr:latest-amd64
    use: buildx
    skip_push: "false"
    build_flag_templates:
    - "--build-arg=VERSION={{.Version}}"
    - "--build-arg=COMMIT_HASH={{.FullCommit}}"
    - "--build-arg=BUILD_DATE={{.Date}}"
    - "--platform=linux/amd64"
    extra_files:
      - go.mod
      - go.sum
      - pkg
      - cmd
      - web
      - embed.go
  - image_templates:
      - public.ecr.aws/prabhat/tf-goreleaser-ecr:latest-arm64
    use: buildx
    skip_push: "false"
    build_flag_templates:
    - "--build-arg=VERSION={{.Version}}"
    - "--build-arg=COMMIT_HASH={{.FullCommit}}"
    - "--build-arg=BUILD_DATE={{.Date}}"
    - "--platform=linux/arm64/v8"
    extra_files:
      - go.mod
      - go.sum
      - pkg
      - cmd
      - web
      - embed.go
  - image_templates:
      - public.ecr.aws/prabhat/tf-goreleaser-ecr:latest-armv7 
    use: buildx
    skip_push: "false"
    build_flag_templates:
    - "--build-arg=VERSION={{.Version}}"
    - "--build-arg=COMMIT_HASH={{.FullCommit}}"
    - "--build-arg=BUILD_DATE={{.Date}}"
    - "--platform=linux/arm/v7"
    extra_files:
      - go.mod
      - go.sum
      - pkg
      - cmd
      - web
      - embed.go
docker_manifests:
- id: tf-goreleaser-ecr_docker

  # Name template for the manifest.
  # Defaults to empty.
  name_template: public.ecr.aws/prabhat/tf-goreleaser-ecr:{{ .Version }}

  # Image name templates to be added to this manifest.
  # Defaults to empty.
  image_templates:
  - public.ecr.aws/prabhat/tf-goreleaser-ecr:{{ .Version }}-amd64
  - public.ecr.aws/prabhat/tf-goreleaser-ecr:{{ .Version }}-arm64
  - public.ecr.aws/prabhat/tf-goreleaser-ecr:{{ .Version }}-armv7
- id: tf-goreleaser-ecr-latest

  # Name template for the manifest.
  # Defaults to empty.
  name_template: public.ecr.aws/prabhat/tf-goreleaser-ecr:latest

  # Image name templates to be added to this manifest.
  # Defaults to empty.
  image_templates:
  - public.ecr.aws/prabhat/tf-goreleaser-ecr:latest-amd64
  - public.ecr.aws/prabhat/tf-goreleaser-ecr:latest-arm64
  - public.ecr.aws/prabhat/tf-goreleaser-ecr:latest-armv7
# https://goreleaser.com/customization/homebrew/
brews:
  - name: tf-goreleaser-ecr
    tap:
      owner: prabhatsharma
      name: homebrew-tap
      # token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    folder: Formula
    homepage: "https://github.com/prabhatsharma/tf-goreleaser-ecr"
    description: |
      tf-goreleaser-ecr is a sample CI/CD pipeline using Terraform and goreleaser
    license: "Apache-2.0"

# snapcrafts:
#   - id: tf-goreleaser-ecr-snap
#     name: tf-goreleaser-ecr-snap
#     summary: tf-goreleaser-ecr Search engine. A lightweight alternative to elasticsearch.
#     description: |
#       tf-goreleaser-ecr is a search engine that does full text indexing. It is a lightweight
#       alternative to elasticsearch that requires significantly less resources. It uses
#       bluge as the underlying indexing library.

#       It is very simple and easy to operate as opposed to elasticsearch which
#       requires a couple dozen knobs to understand and tune.

#       It is a drop-in replacement for elasticsearch if you are just ingesting
#       data using APIs and searching using kibana (Kibana is not supported with
#       tf-goreleaser-ecr. tf-goreleaser-ecr provides its own UI).

#     license: Apache-2.0
#     grade: stable
#     confinement: classic
#     base: core18

#     replacements:
#       darwin: Darwin
#       linux: Linux
#       windows: Windows
#       386: i386
#       amd64: x86_64

    # Whether to publish the snap to the snapcraft store.
    # Remember you need to `snapcraft login` first.
    # Defaults to false.
    # publish: false

